FROM cgr.dev/chainguard/wolfi-base:latest@sha256:9608820b6ea4da8bcf16989dac37a280f8f1fa0022efc45b5ed4b1ac1f634a79
# Thanks to Nuno do Carmo for the initial prototype

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the Toolbox or Distrobox command" \
      summary="A blank Wolfi distrobox, suitable for development" \
      maintainer="jorge.castro@gmail.com"

ARG IMAGE_NAME="${IMAGE_NAME:-wolfi-toolbox}"

COPY ./toolboxes/wolfi-toolbox/packages.wolfi \
     ./toolboxes/wolfi-toolbox/packages.wolfi-dx \
     /tmp/

# Update image
RUN apk update && \
    apk upgrade

# Add optional packages
RUN grep -v '^#' /tmp/packages.wolfi | xargs apk add && \
    if [[ "${IMAGE_NAME}" =~ "dx" ]]; then \
        grep -v '^#' /tmp/packages.wolfi-dx | xargs apk add \
    ; fi && \
    echo "#!/bin/sh" >> /usr/bin/pinentry && \
    echo "exit 0" >> /usr/bin/pinentry && \
    chmod +x /usr/bin/pinentry

# Get Distrobox-host-exec and host-spawn
RUN git clone https://github.com/89luca89/distrobox.git --single-branch /tmp/distrobox && \
    cp /tmp/distrobox/distrobox-host-exec /usr/bin/distrobox-host-exec && \
    cp /tmp/distrobox/distrobox-export /usr/bin/distrobox-export && \
    cp /tmp/distrobox/distrobox-init /usr/bin/entrypoint && \
    wget https://github.com/1player/host-spawn/releases/download/$(cat /tmp/distrobox/distrobox-host-exec | grep host_spawn_version= | cut -d "\"" -f 2)/host-spawn-$(uname -m) -O /usr/bin/host-spawn && \
    chmod +x /usr/bin/host-spawn && \
    rm -drf /tmp/distrobox

# Make some symlinks
RUN mkdir -p /usr/local/bin  && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree

# Change root shell to BASH
RUN sed -i -e '/^root/s/\/bin\/ash/\/bin\/bash/' /etc/passwd

# Delete nonroot user
RUN userdel nonroot && rm -rf /home/nonroot
